# mode(debug or release)
mode:
  debug

# 数据库
db:
  driver: mysql
  addr: root:123456@tcp(8.136.142.201:3306)/qasystem?charset=utf8mb4&parseTime=True&loc=Local
# redis
redis:
  host: 8.136.142.201
  port: 6379
  password: 123456
  db: 0
  pool_size: 100

# jwt认证密钥
jwtKey: salt20201206

# 端口
address: :9090
#
## 七牛云存储
#AccessKey : XdET1lY5VuL2VJYLrhOFhgkuEMnub8TWeNLMc5Oy
#SecretKey : prliESBDhNdu2TBP0rDldLBlPBgOmW91reJ9ISC3
#Bucket : ustcqa
#QiniuServer : http://ql7gtjj87.hd-bkt.clouddn.com/