# mode(debug or release)
mode:
  debug

# 数据库
db:
  driver: mysql
  addr: root:root@tcp(127.0.0.1:3306)/qasystem?charset=utf8mb4&parseTime=True&loc=Local

# jwt认证密钥
jwtKey: salt20201206

# 端口
address: :9090
#
## 七牛云存储
#AccessKey : XdET1lY5VuL2VJYLrhOFhgkuEMnub8TWeNLMc5Oy
#SecretKey : prliESBDhNdu2TBP0rDldLBlPBgOmW91reJ9ISC3
#Bucket : ustcqa
#QiniuServer : http://ql7gtjj87.hd-bkt.clouddn.com/